medical_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: your_password_here
      port: 5432
      dbname: medical_dw
      schema: analytics
      threads: 4
  target: dev
