version: 2

models:
  - name: yolo_detections
    description: "Processed YOLO detection results with product categories"
    columns:
      - name: message_id
        tests:
          - not_null
      - name: product_name
        tests:
          - not_null
      - name: product_category
        tests:
          - not_null
